# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('article_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('read', models.PositiveIntegerField(default=0)),
                ('collect', models.PositiveIntegerField(default=0)),
                ('command', models.PositiveIntegerField(default=0)),
                ('image', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticalDraft',
            fields=[
                ('articalDraft_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticalTag',
            fields=[
                ('tag_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=64)),
                ('tag_abstract', models.CharField(default='', max_length=128)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('tag_img', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['createTime'],
            },
        ),
        migrations.CreateModel(
            name='haveFunUser',
            fields=[
                ('user_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=1)),
                ('age', models.PositiveIntegerField(default=18)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('user_type', models.IntegerField(choices=[(0, '超级用户'), (1, '普通用户')], default=1)),
                ('passwd', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='userHeadImage',
            fields=[
                ('image_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='head_images')),
                ('uploaded_by', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='articaltag',
            name='createdByUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haveFun.haveFunUser'),
        ),
        migrations.AddField(
            model_name='articaldraft',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haveFun.haveFunUser'),
        ),
        migrations.AddField(
            model_name='articaldraft',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haveFun.ArticalTag'),
        ),
        migrations.AddField(
            model_name='artical',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haveFun.haveFunUser'),
        ),
        migrations.AddField(
            model_name='artical',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haveFun.ArticalTag'),
        ),
        migrations.AlterUniqueTogether(
            name='articaltag',
            unique_together=set([('tag_id', 'tag_name', 'createdByUser', 'createTime', 'tag_abstract', 'tag_img')]),
        ),
    ]
