# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haveFun', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articaltag',
            options={'ordering': ['createTime']},
        ),
        migrations.AlterUniqueTogether(
            name='articaltag',
            unique_together=set([('tag_id', 'tag_name', 'createdByUser', 'createTime', 'tag_abstract', 'tag_img')]),
        ),
    ]
