# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haveFun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userheadimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='head_images/'),
        ),
    ]
