# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haveFun', '0002_auto_20171215_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articaldraft',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articaltag',
            name='tag_img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='havefunuser',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
