# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haveFun', '0002_articalheadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articalheadimage',
            name='uploaded_artical_id',
            field=models.IntegerField(),
        ),
    ]
