# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haveFun', '0002_auto_20180125_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userheadimage',
            name='owner',
        ),
        migrations.AlterField(
            model_name='userheadimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='head_images'),
        ),
    ]
