# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haveFun', '0004_articalheadimage_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articalheadimage',
            old_name='uploaded_artical_id',
            new_name='uploaded_by',
        ),
    ]
