# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haveFun', '0006_articaltagimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articaltagimage',
            name='filename',
            field=models.CharField(default='', max_length=100),
        ),
    ]
